name: Draft Release
on:
  workflow_dispatch:
    inputs:
      target:
        description: "The owner/repo GitHub target"
        required: true
      branch:
        description: "The branch to target (defaults to default branch)"
        required: false
      version_spec:
        description: "New Version Spec"
        default: "next"
        required: false
      post_version_spec:
        description: "Post Version Specifier"
        required: false
      since:
        description: "Use PRs with activity since this date or git reference"
        required: false
      since_last_stable:
        description: "Use PRs with activity since the last stable git tag"
        required: false
        type: boolean
      steps_to_skip:
        description: "Comma separated list of steps to skip"
        required: false
jobs:
  draft_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
    env:
      VERSION_SPEC: ${{ github.event.inputs.version_spec }}
      POST_VERSION_SPEC: ${{ github.event.inputs.post_version_spec }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/common

      - name: Create Draft GitHub Release
        id: draft-release
        uses: ./.github/actions/draft-release
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          version_spec: ${{ github.event.inputs.version_spec }}
          post_version_spec: ${{ github.event.inputs.post_version_spec }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.inputs.since_last_stable }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: "** Next Step **"
        run: |
          echo "Run the "Publish Release" Workflow with Release Url:"
          echo ${{ steps.draft-release.outputs.release_url }}
          echo "## Next Step" >> $GITHUB_STEP_SUMMARY
          echo "Run the "Publish Release" Workflow with Release Url:" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.draft-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
