name: "Step 1: Draft Changelog"
on:
  workflow_dispatch:
    inputs:
      target:
        description: "The owner/repo GitHub target"
        required: true
      branch:
        description: "The branch to target (defaults to default branch)"
        required: false
      version_spec:
        description: "New Version Spec"
        default: "next"
        required: false
      since:
        description: "Use PRs with activity since this date or git reference"
        required: false
      since_last_stable:
        description: "Use PRs with activity since the last stable git tag"
        type: boolean
        required: false
jobs:
  draft_changelog:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/common

      - name: Draft Changelog
        id: draft-changelog
        uses: ./.github/actions/draft-changelog
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          version_spec: ${{ github.event.inputs.version_spec }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.inputs.since_last_stable }}

      - name: "** Next Step **"
        run: |
          echo "Review PR: ${{ steps.draft-changelog.outputs.pr_url }}"
          echo "## Next Step" >> $GITHUB_STEP_SUMMARY
          echo "Review PR: ${{ steps.draft-changelog.outputs.pr_url }}" >> $GITHUB_STEP_SUMMARY
