name: "Step 2: Full Release"
on:
  workflow_dispatch:
    inputs:
      target:
        description: "The owner/repo GitHub target"
        required: true
      branch:
        description: "The branch to target (defaults to default branch)"
        required: false
      version_spec:
        description: "New Version Spec"
        required: false
        default: "next"
      post_version_spec:
        description: "Post Version Specifier"
        required: false
      since:
        description: "Use PRs with activity since this date or git reference"
        required: false
      since_last_stable:
        description: "Use PRs with activity since the last stable git tag"
        required: false
        type: boolean
      steps_to_skip:
        description: "Comma separated list of steps to skip"
        required: false

jobs:
  full_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
    env:
      VERSION_SPEC: ${{ github.event.inputs.version_spec }}
      POST_VERSION_SPEC: ${{ github.event.inputs.post_version_spec }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/common

      - name: Create Draft GitHub Release
        id: draft-release
        uses: ./.github/actions/draft-release
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          version_spec: ${{ github.event.inputs.version_spec }}
          post_version_spec: ${{ github.event.inputs.post_version_spec }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.intputs.since_last_stable }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: Publish Release
        id: publish-release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          PYPI_TOKEN_MAP: ${{ secrets.PYPI_TOKEN_MAP }}
          TWINE_USERNAME: __token__
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: ./.github/actions/publish-release
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          release_url: ${{ steps.draft-release.outputs.release_url }}

      - name: "** Next Step **"
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.publish-release.outputs.release_url }}
          echo "## Next Step" >> $GITHUB_STEP_SUMMARY
          echo "Verify the final release" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.publish-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
          if [ ! -z "${{ steps.publish-release.outputs.pr_url }}" ]; then
             echo "Merge the forwardport PR"
             echo ${{ steps.publish-release.outputs.pr_url }}
             echo "Merge the forwardport PR" >> $GITHUB_STEP_SUMMARY
             echo ${{ steps.publish-release.outputs.pr_url }} >> $GITHUB_STEP_SUMMARY
          fi

      - name: "** Failure Message **"
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.draft-release.outputs.release_url }}
          echo "## Failure Message" >> $GITHUB_STEP_SUMMARY
          echo ":x: Failed to Publish the Draft Release Url:" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.draft-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
