name: "Step 2: Full Release"
on:
  workflow_dispatch:
    inputs:
      target:
        description: "The owner/repo GitHub target"
        required: false
      branch:
        description: "The target branch"
        required: false
      release_url:
        description: "The URL of the draft GitHub release"
        required: false
      steps_to_skip:
        description: "Comma separated list of steps to skip"
        required: false

jobs:
  full_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/common

      - name: Create Draft GitHub Release
        id: draft-release
        uses: ./.github/actions/draft-release
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ github.event.inputs.release_url }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: Publish Release
        id: publish-release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          PYPI_TOKEN_MAP: ${{ secrets.PYPI_TOKEN_MAP }}
          TWINE_USERNAME: __token__
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: ./.github/actions/publish-release
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          release_url: ${{ steps.draft-release.outputs.release_url }}

      - name: "** Next Step **"
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.publish-release.outputs.release_url }}
          echo "## Next Step" >> $GITHUB_STEP_SUMMARY
          echo "Verify the final release" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.publish-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
          if [ ! -z "${{ steps.publish-release.outputs.pr_url }}" ]; then
             echo "Merge the forwardport PR"
             echo ${{ steps.publish-release.outputs.pr_url }}
             echo "Merge the forwardport PR" >> $GITHUB_STEP_SUMMARY
             echo ${{ steps.publish-release.outputs.pr_url }} >> $GITHUB_STEP_SUMMARY
          fi

      - name: "** Failure Message **"
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.draft-release.outputs.release_url }}
          echo "## Failure Message" >> $GITHUB_STEP_SUMMARY
          echo ":x: Failed to Publish the Draft Release Url:" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.draft-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
